### ISSUE TITLE
Addition that could be cool.

### ISSUE THREAD

**Issue by JarodEphec** [4zv4l/ztictactoe#1]
Hello,

I"ve tried your litle game by installing zig from my beloved snap store :)
First thing that annoyed me is that you need to put a number to play, I really find it unintuitive, I wonder if you can add the possibility to actually click on the board ? I know it's possible.
Second things, and this one is an easy fix, you shoud add, for exemple, a system ("clear");. This way your game will look less of a novice work.

Regards

**Comment by 4zv4l** [comment]
lmao Jarod xD
yeah I can add the clear but `system("clear")` is in C and not in Zig :wink: 
for the mouse click, I won't implement it the purpose of this soft is to be as simple as possible.
